-- CAI Platform initial schema (PostgreSQL)
-- Migrated from the legacy Salesforce (Apex) retail-banking org.

-- Client: relational redesign of the Salesforce Account Person Account.
CREATE TABLE client (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    sin_hash          VARCHAR(64),
    date_of_birth     DATE,
    email             VARCHAR(255),
    phone             VARCHAR(255),
    province          VARCHAR(255),
    kyc_status        VARCHAR(255),
    kyc_verified_date DATE
);

-- Dedupe lookups (ClientSelector.bySinHashAndDob / withStaleKyc).
CREATE INDEX idx_client_sin_hash ON client (sin_hash);
CREATE INDEX idx_client_sin_hash_dob ON client (sin_hash, date_of_birth);

-- EscalationCase: local model of the Salesforce standard Case created on
-- urgent dispute escalation (could later be a ServiceNow/Jira integration).
CREATE TABLE escalation_case (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject   VARCHAR(255),
    priority  VARCHAR(255),
    origin    VARCHAR(255),
    client_id BIGINT REFERENCES client (id)
);

-- LoanApplication: from Loan_Application__c.
CREATE TABLE loan_application (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_number    VARCHAR(255),
    amount                NUMERIC(18, 2),
    offered_rate          NUMERIC(18, 4),
    amortization_months   INTEGER,
    annual_income         NUMERIC(18, 2),
    monthly_housing_costs NUMERIC(18, 2),
    monthly_debt_payments NUMERIC(18, 2),
    status                VARCHAR(255),
    gds_ratio             NUMERIC(18, 4),
    tds_ratio             NUMERIC(18, 4),
    decline_reason        VARCHAR(255),
    submitted_date        TIMESTAMP,
    client_id             BIGINT REFERENCES client (id)
);

-- TransactionDispute: from Transaction_Dispute__c.
CREATE TABLE transaction_dispute (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispute_number     VARCHAR(255),
    client_id          BIGINT NOT NULL REFERENCES client (id),
    card_last4         VARCHAR(4),
    amount             NUMERIC(18, 2),
    reason_code        VARCHAR(40),
    card_present       BOOLEAN NOT NULL DEFAULT FALSE,
    status             VARCHAR(255),
    filed_date         TIMESTAMP,
    -- SLA due date stays a DATE (see TransactionDispute javadoc / MIGRATION_NOTES).
    sla_due_date       DATE,
    escalation_case_id BIGINT REFERENCES escalation_case (id)
);
